// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0nlBSrd5XWHBUUHAqYDgY-gf_tFIwSlE',
    appId: '1:848508544309:web:00a59a479197bbde91187c',
    messagingSenderId: '848508544309',
    projectId: 'tracker-2e84f',
    authDomain: 'tracker-2e84f.firebaseapp.com',
    storageBucket: 'tracker-2e84f.firebasestorage.app',
    measurementId: 'G-Z6FCG2RR5D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1rB23WrbBW2BVDCPz1w5ajTLRpKbJPtU',
    appId: '1:848508544309:android:6d76e870209a6ead91187c',
    messagingSenderId: '848508544309',
    projectId: 'tracker-2e84f',
    storageBucket: 'tracker-2e84f.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0nlBSrd5XWHBUUHAqYDgY-gf_tFIwSlE',
    appId: '1:848508544309:web:37bdb69a8a63eddc91187c',
    messagingSenderId: '848508544309',
    projectId: 'tracker-2e84f',
    authDomain: 'tracker-2e84f.firebaseapp.com',
    storageBucket: 'tracker-2e84f.firebasestorage.app',
    measurementId: 'G-NV86PVGRHV',
  );
}
